<a href="https://colab.research.google.com/github/Leo-hen/ISYS5002/blob/main/week-10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas requests beautifulsoup4

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (4.13.5)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests) (2026.7.22)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (4.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd  # For data manipulation
import requests  # For making HTTP requests
from bs4 import BeautifulSoup  # For parsing HTML content
import time  # For adding delays between requests (ethical scraping)

In [4]:
# TODO: Define your headers to identify yourself
headers = {
    'User-Agent': 'Mozilla/5.0 (Educational purpose scraper)',
    'Accept': 'text/html,application/xhtml+xml'
}

# URL of the page we want to scrape
url = 'http://books.toscrape.com/'

# TODO: Make a request to the website
response = requests.get(url, headers=headers)

# Check if the request was successful
if response.status_code == 200:
    print(f"Successfully downloaded the page! Content length: {len(response.text)} characters")
else:
    print(f"Failed to download the page. Status code: {response.status_code}")

# Let's see what the raw HTML looks like (just the first 500 characters)
print(response.text[:500])

Successfully downloaded the page! Content length: 51294 characters
<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en-us" class="no-js"> <!--<![endif]-->
    <head>
        <title>
    All products | Books to Scrape - Sandbox
</title>

        <meta http-equiv="content-type" content="text/html; charset=UTF-8" /

In [5]:
# TODO: Create a BeautifulSoup object
soup = BeautifulSoup(response.text, 'html.parser')

# Let's check the title of the page
page_title = soup.title.text
print(f"Page title: {page_title}")

Page title:
    All products | Books to Scrape - Sandbox

In [6]:
# Find all book containers on the page
book_containers = soup.find_all('article', class_='product_pod')
print(f"Found {len(book_containers)} books on this page")

# Lists to store our data
titles = []
prices = []
ratings = []

# TODO: Extract information from each book container
for book in book_containers:
    # Extract title
    title = book.h3.a['title']
    titles.append(title)

    # Extract price
    price = book.find('p', class_='price_color').text
    prices.append(price)

    # Extract star rating (contained in the class name)
    star_rating = book.find('p', class_='star-rating')['class'][1]
    ratings.append(star_rating)

# Display the first 5 items from each list
for i in range(5):
    print(f"Book {i+1}: {titles[i]}, Price: {prices[i]}, Rating: {ratings[i]}")

Found 20 books on this page
Book 1: A Light in the Attic, Price: Â£51.77, Rating: Three
Book 2: Tipping the Velvet, Price: Â£53.74, Rating: One
Book 3: Soumission, Price: Â£50.10, Rating: One
Book 4: Sharp Objects, Price: Â£47.82, Rating: Four
Book 5: Sapiens: A Brief History of Humankind, Price: Â£54.23, Rating: Five

In [7]:
# TODO: Create a DataFrame from the scraped data
books_data = {
    'Title': titles,
    'Price': prices,
    'Rating': ratings
}

books_df = pd.DataFrame(books_data)

# Show the DataFrame
books_df

                                                Title    Price Rating
0                                A Light in the Attic  Â£51.77  Three
1                                  Tipping the Velvet  Â£53.74    One
2                                          Soumission  Â£50.10    One
3                                       Sharp Objects  Â£47.82   Four
4               Sapiens: A Brief History of Humankind  Â£54.23   Five
5                                     The Requiem Red  Â£22.65    One
6   The Dirty Little Secrets of Getting Your Dream...  Â£33.34   Four
7   The Coming Woman: A Novel Based on the Life of...  Â£17.93  Three
8   The Boys in the Boat: Nine Americans and Their...  Â£22.60   Four
9                                     The Black Maria  Â£52.15    One
10     Starving Hearts (Triangular Trade Trilogy, #1)  Â£13.99    Two
11                              Shakespeare's Sonnets  Â£20.66   Four
12                                        Set Me Free  Â£17.46   Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...  Â£52.29   Five
14                          Rip it Up and Start Again  Â£35.02   Five
15  Our Band Could Be Your Life: Scenes from the A...  Â£57.25  Three
16                                               Olio  Â£23.88    One
17  Mesaerion: The Best Science Fiction Stories 18...  Â£37.59    One
18                       Libertarianism for Beginners  Â£51.33    Two
19                            It's Only the Himalayas  Â£45.17    Two

In [13]:
# TODO: Clean the price column (remove currency symbol and convert to float)
books_df['Price'] = books_df['Price'].str.replace('Â£', '').astype(float)

# TODO: Convert ratings to numeric values
rating_mapping = {
    'One': 1,
    'Two': 2,
    'Three': 3,
    'Four': 4,
    'Five': 5
}
books_df['Rating'] = books_df['Rating'].map(rating_mapping)

# Show the updated DataFrame
# Use print(..) if using VSC
books_df

                                                Title  Price  Rating
0                                A Light in the Attic  51.77       3
1                                  Tipping the Velvet  53.74       1
2                                          Soumission  50.10       1
3                                       Sharp Objects  47.82       4
4               Sapiens: A Brief History of Humankind  54.23       5
5                                     The Requiem Red  22.65       1
6   The Dirty Little Secrets of Getting Your Dream...  33.34       4
7   The Coming Woman: A Novel Based on the Life of...  17.93       3
8   The Boys in the Boat: Nine Americans and Their...  22.60       4
9                                     The Black Maria  52.15       1
10     Starving Hearts (Triangular Trade Trilogy, #1)  13.99       2
11                              Shakespeare's Sonnets  20.66       4
12                                        Set Me Free  17.46       5
13  Scott Pilgrim's Precious Little Life (Scott Pi...  52.29       5
14                          Rip it Up and Start Again  35.02       5
15  Our Band Could Be Your Life: Scenes from the A...  57.25       3
16                                               Olio  23.88       1
17  Mesaerion: The Best Science Fiction Stories 18...  37.59       1
18                       Libertarianism for Beginners  51.33       2
19                            It's Only the Himalayas  45.17       2

In [14]:
# Display basic statistics
books_df.describe()

# TODO: Calculate average price by rating
avg_price_by_rating = books_df.groupby('Rating')['Price'].mean().sort_index()
print("Average price by rating:")
avg_price_by_rating

# Use print(..) if using VSC

Average price by rating:

Rating
1    40.018333
2    36.830000
3    42.316667
4    31.105000
5    39.750000
Name: Price, dtype: float64

In [15]:
# Your code here
# Hint: The pagination URLs follow this pattern: 'http://books.toscrape.com/catalogue/page-{page_num}.html'

all_titles = []
all_prices = []
all_ratings = []

# Loop through multiple pages
for page_num in range(1, 4):  # Pages 1, 2, and 3
    # Construct the URL for each page
    if page_num == 1:
        page_url = 'http://books.toscrape.com/'
    else:
        page_url = f'http://books.toscrape.com/catalogue/page-{page_num}.html'

    # Add a small delay to be polite
    time.sleep(1)

    # Make the request
    response = requests.get(page_url, headers=headers)

    # Check if successful
    if response.status_code == 200:
        print(f"Successfully scraped page {page_num}")

        # Parse the page
        soup = BeautifulSoup(response.text, 'html.parser')

        # Extract book information
        # (Your extraction code here)
    else:
        print(f"Failed to scrape page {page_num}")

Successfully scraped page 1
Successfully scraped page 2
Successfully scraped page 3

In [16]:
# TODO: Save the DataFrame to a CSV file
books_df.to_csv('scraped_books.csv', index=False)
print("Data saved to 'scraped_books.csv'")

Data saved to 'scraped_books.csv'